spring:
  application:
    name: PicPle

  datasource:
    url: jdbc:h2:file:~/testdb  # C:\Users\<사용자>\testdb.mv.db 이용
    driver-class-name: org.h2.Driver
    username: sa
    password:

  #datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://picple.cdwkmu84aawc.ap-northeast-2.rds.amazonaws.com:3306/picple?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #username: admin
    #password:  picpledev00!!

  h2:
    console:
      enabled: true
      path: /h2-console #콘솔접속 : http://localhost:8080/h2-console

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace