-- 명사(NOUN) 태그
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '카페');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '음식점');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '자연경관');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '공공기관');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '박물관');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '미술관');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '공공시설');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '극장');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '영화관');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', 'PC방');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '주점');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '노래방');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '보드게임 카페');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '방탈출 카페');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '애견카페');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '편의점');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '마트');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '볼링장');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '당구장');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '농구장');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '축구장');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '체육시설');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '술집');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '대학교');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '중학교');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '초등학교');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '유치원');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '학원');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '공원');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '주차장');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '캠핑장');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '길거리');
INSERT INTO tag (tag_type, name) VALUES ('NOUN', '야외공연장');

-- 형용사(ADJECTIVE) 태그
INSERT INTO tag (tag_type, name) VALUES ('ADJECTIVE', '친절한');
INSERT INTO tag (tag_type, name) VALUES ('ADJECTIVE', '아늑한');
INSERT INTO tag (tag_type, name) VALUES ('ADJECTIVE', '조용한');
INSERT INTO tag (tag_type, name) VALUES ('ADJECTIVE', '넓은');
INSERT INTO tag (tag_type, name) VALUES ('ADJECTIVE', '깔끔한');
INSERT INTO tag (tag_type, name) VALUES ('ADJECTIVE', '특별한');
INSERT INTO tag (tag_type, name) VALUES ('ADJECTIVE', '기억에 남는');
INSERT INTO tag (tag_type, name) VALUES ('ADJECTIVE', '낭만적인');
INSERT INTO tag (tag_type, name) VALUES ('ADJECTIVE', '신나는');
INSERT INTO tag (tag_type, name) VALUES ('ADJECTIVE', '멋진');
INSERT INTO tag (tag_type, name) VALUES ('ADJECTIVE', '아름다운');
INSERT INTO tag (tag_type, name) VALUES ('ADJECTIVE', '맛있는');
INSERT INTO tag (tag_type, name) VALUES ('ADJECTIVE', '향기로운');
